#! /bin/sh

# Recommend enable multilib mirror
# edit /etc/pacman.conf file
# Search for #[multilib] and #Include = /etc/pacman.d/mirrorlist. And uncomment these lines 

pacman -Sy \
baobab \
composer \
cups \
dialog \
docker \
docker-compose \
dosfstools \
eog \
evince \
file-roller \
firefox \
firefox-i18n-pt-br \
flameshot \
flatpak \
gamemode \
gdm \
gnome-backgrounds \
gnome-calculator \
gnome-calendar \
gnome-characters \
gnome-color-manager \
gnome-contacts \
gnome-disk-utility \
gnome-font-viewer \
gnome-icon-theme-extras \
gnome-keyring \
gnome-menus \
gnome-software-packagekit-plugin \
gnome-system-monitor \
gnome-themes-extra \
gnome-tweaks \
grim \
gst-libav \
gst-plugins-good \
gvfs \
gvfs-afc \
gvfs-goa \
gvfs-google \
gvfs-mtp \
gvfs-nfs \
gvfs-smb \
keychain \
libpackagekit-glib \
mtools \
neovim \
network-manager-applet \
networkmanager \
nodejs \
noto-fonts \
noto-fonts-emoji \
npm \
ntfs-3g \
numlockx \
os-prober \
packagekit \
pacman-contrib \
papirus-icon-theme \
pavucontrol \
php-fpm \
php-gd \
php-pgsql \
php-redis \
piper \
python-nautilus \
python-pynvim \
sudo \
sushi \
tilix \
tracker \
tracker-miners \
tracker3 \
tracker3-miners \
transmission-gtk \
ttf-baekmuk \
ttf-fira-code \
ttf-hannom \
ttf-joypixels \
ttf-liberation \
ttf-roboto \
ttf-roboto-mono \
vlc \
wget \
wireless_tools \
wpa_supplicant \
xclip \
xdg-desktop-portal \
xdg-user-dirs \
xdg-user-dirs-gtk \
xdg-utils \
xorg-xclipboard \
yarn \
zsh \
zsh-completions 


# enable network
systemctl enable NetworkManager

# enable cups
systemctl enable cups.service

# enable gdm
systemctl enable gdm.service

# enable docker
systemctl enable docker.service
